server:
  port: 8888
spring:
  application:
    name: greeting-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aroldocosta/git-config-server  
          #username: username
          #password: password
          search-paths:
          - 'greeting-service*'
          